language: ruby
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.10
  - 2.3.8
  - 2.4.10
  - 2.5.8
  - 2.6.6
  - ruby-head
before_install:
  - |
    if [[ `ruby -v` =~ 2\.[0-2]\.[0-9]+ ]]; then
      gem install rubygems-update -v '<3' && update_rubygems
      gem install bundler -v '<2'
    else
      gem update --system
      gem update bundler
    fi
env:
  global:
  - secure: J+Q57/BXu3MwnjG2/F8LuNUdv0YYDi6D1BlnciQWakB9gjUCgu1amoqeZx4CsMEQRl8R9Fm2Pmjvng3qQcX5z2kESOWXLNvL7f75/xU1KacpzYUllCGaJW4xNTgvdp7x4FSYYyPNTxTky3xmsvo4NedSVM+RRdDybPE3hALmVr6XlvyBK0j9EaRERCAiqmQdOw5DwD1cLtVeGukvYFuAHsjF1sfGU8bi8S6WuWstOg4ZplNPR3p2KAA3hLdh4zDzKLG5M9F9ZrD77rIMHlLLuTmiPTvA1sooKqh3KNqfji/JIP/Kgtj9b1PT82MWIZlRdw3QPBXC2rZZakEi+PGBQuDbl/wOZaOyvBUvKszPZctTWnkHBNNIIvcPM8n8yXPtn6tEgpr2nGqbxm4iBj+rpG4AtjuC9+rqawrK1VzypeWCf02wiL2sRa8SC5ElKcRxtWmddO7UCuR0n4N2PhTcbvKsx3ngMxxUOpgSWSxIb61KbHonlLnWNmzoafUdtzrth4KUwwNirhl7SUBT165M6BZis0FgltifYv7mAc02axQfzy4gU6IzrS8GF/k/szxiMyfkC5YPkcwhlC9IkW6ISnVUGVSqwXmdS2UyTlYubPsWeEBOL1/X0ZLPiD92zoJw8xX3sElGAg8uNKXPpWSKPkgf0ymDuQBjWKooYtgQQqg=
  - secure: U4zfv1DmbSPUIXYwwar7Q3Od/TNH+Hf7WaNPafnojAilChJFyWlYKbDEbwGiAmQdk0kT3aCmbw+inJyXb8nqWE/Y2+tX4k3W3zR1K2Y9b0RT5OGM5rlM5tXZqwP7xAcJ54+SUVNHn4AlNeUQ1Sfrj6GW73rDWmmrvHE9NV0aeYsPDmrETEqSwYIYftBY2r6Rv9I11ZcJEWOflgr4C432PlThcnevvhgNClJW1OA9NmHOGO7fb1SoyZW0G8DdhlSikjxnj7h0CUln+H8tqozcGO8TbXOelCdKW+fakei2FdBe6m3NHqVj4m3xpWLQHiyD4RtIkV1TAcgEdcJRe4cCwdbhZCVKGUHIm+wvJpr/unxG7FHLN+KXPtohJzLueSZlWgg3jvMrJV/iXsNmzDOFvDiYsC1W16zO9jaUqk6copzQouwW+/wfQGbQh1ujnhc+Jnkmo9Xfk9fLYlqHn0VE6rhjjINxdT5fWMcUsOlSxAli8HKb2utH8cZrqtgu+Yrku3dzz54hQamJzzU5XsCRpqBjIZkXu2vrLMqI/+h3yPT3ZmVrjpCe9GPEI9xDLsKyUnCYOVzUjuojpV21n+s0BmRt0C3Yg+cKl6O0K1rSQTU5Fh4erCLuaSWNTLNh8eYqowxIjUq5jaQEFzr47tfmMuZulSGzZlTz8qttDB3hRqU=
